import "dotenv/config";
import { and, eq, isNotNull } from "drizzle-orm";
import { db } from "../src/lib/db/client";
import { meals, mealIngredients } from "../src/lib/db/schema";

/**
 * Local-dev-only seed data: hand-authored (not LLM-generated, not priced via
 * Pepesto) so tonight's labeling session has real variety without spending
 * any API credits. Prices here are plausible placeholders, NOT fetched from
 * any pricing adapter. Real pricing only ever comes from priceApprovedMeals()
 * (src/lib/pricing/priceApproved.ts), triggered manually via the queue page
 * or `npm run pipeline:price`. Once ANTHROPIC_API_KEY is set, the real
 * pipeline (npm run pipeline:generate) can supplement or replace this list.
 */
interface DemoMeal {
  name: string;
  description: string;
  primaryProtein: string;
  isClassic: boolean;
  instructions: string[];
  ingredients: { name: string; quantity: string }[];
}

const DEMO_MEALS: DemoMeal[] = [
  // --- Beef ---
  {
    name: "Spaghetti Bolognese",
    description: "Classic beef ragu over spaghetti.",
    primaryProtein: "beef",
    isClassic: true,
    instructions: [
      "Brown 400g beef mince in a large pan.",
      "Add chopped onion, carrot, celery and garlic, cook until soft.",
      "Stir in a tin of chopped tomatoes and a splash of stock, simmer 25 minutes.",
      "Cook 300g spaghetti, combine and serve with parmesan.",
    ],
    ingredients: [
      { name: "beef mince", quantity: "400g" },
      { name: "spaghetti", quantity: "300g" },
      { name: "chopped tomatoes", quantity: "1 tin" },
      { name: "onion", quantity: "1" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "carrot", quantity: "1" },
      { name: "celery", quantity: "2 sticks" },
      { name: "beef stock", quantity: "150ml" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "parmesan", quantity: "40g" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Beef and Ale Stew",
    description: "Slow-cooked chunks of beef in a rich ale gravy.",
    primaryProtein: "beef",
    isClassic: false,
    instructions: [
      "Brown 500g diced beef shin in batches.",
      "Add onion, carrot and a bottle of ale, bring to a simmer.",
      "Cover and cook low for 2.5 hours until tender.",
      "Serve with mash or crusty bread.",
    ],
    ingredients: [
      { name: "diced beef shin", quantity: "500g" },
      { name: "ale", quantity: "330ml" },
      { name: "carrots", quantity: "3" },
      { name: "onion", quantity: "1" },
      { name: "vegetable oil", quantity: "1 tbsp" },
      { name: "plain flour", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Steak and Chips",
    description: "Pan-seared sirloin with hand-cut chips and peppercorn sauce.",
    primaryProtein: "beef",
    isClassic: false,
    instructions: [
      "Cut and fry chips until golden.",
      "Season two sirloin steaks and sear 2-3 minutes each side.",
      "Rest the steak, deglaze the pan with cream and peppercorns for the sauce.",
      "Serve steak and chips with the sauce.",
    ],
    ingredients: [
      { name: "sirloin steaks", quantity: "2" },
      { name: "potatoes", quantity: "600g" },
      { name: "double cream", quantity: "100ml" },
      { name: "green peppercorns", quantity: "1 tbsp" },
      { name: "vegetable oil", quantity: "2 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Beef Tacos",
    description: "Spiced beef mince tacos with all the toppings.",
    primaryProtein: "beef",
    isClassic: false,
    instructions: [
      "Fry 400g beef mince with taco seasoning.",
      "Warm taco shells or tortillas.",
      "Fill with beef, lettuce, cheese, salsa and soured cream.",
    ],
    ingredients: [
      { name: "beef mince", quantity: "400g" },
      { name: "taco shells", quantity: "8" },
      { name: "cheddar cheese", quantity: "100g" },
      { name: "salsa", quantity: "200g" },
      { name: "taco seasoning", quantity: "1 packet" },
      { name: "lettuce", quantity: "0.5 head" },
      { name: "soured cream", quantity: "100g" },
      { name: "vegetable oil", quantity: "1 tbsp" },
    ],
  },
  {
    name: "Cottage Pie",
    description: "Beef mince in gravy topped with creamy mashed potato.",
    primaryProtein: "beef",
    isClassic: true,
    instructions: [
      "Brown 400g beef mince with onion and carrot.",
      "Add stock and simmer 20 minutes.",
      "Top with mashed potato and bake at 200C for 20 minutes.",
    ],
    ingredients: [
      { name: "beef mince", quantity: "400g" },
      { name: "potatoes", quantity: "700g" },
      { name: "beef stock", quantity: "300ml" },
      { name: "carrots", quantity: "2" },
      { name: "onion", quantity: "1" },
      { name: "butter", quantity: "40g" },
      { name: "milk", quantity: "50ml" },
      { name: "vegetable oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Beef Stir Fry",
    description: "Quick sliced beef and vegetable stir fry.",
    primaryProtein: "beef",
    isClassic: false,
    instructions: [
      "Slice 350g beef strips thinly, marinate in soy sauce.",
      "Stir fry beef in a hot wok until browned, set aside.",
      "Stir fry mixed vegetables, combine with beef and noodles.",
    ],
    ingredients: [
      { name: "beef strips", quantity: "350g" },
      { name: "mixed stir fry vegetables", quantity: "300g" },
      { name: "noodles", quantity: "250g" },
      { name: "soy sauce", quantity: "3 tbsp" },
      { name: "vegetable oil", quantity: "2 tbsp" },
    ],
  },
  {
    name: "Beef Lasagne",
    description: "Layered pasta bake with beef ragu and bechamel.",
    primaryProtein: "beef",
    isClassic: true,
    instructions: [
      "Make a beef ragu as for bolognese.",
      "Make a bechamel sauce with butter, flour and milk.",
      "Layer lasagne sheets, ragu and bechamel, top with cheese.",
      "Bake at 190C for 35 minutes.",
    ],
    ingredients: [
      { name: "beef mince", quantity: "400g" },
      { name: "lasagne sheets", quantity: "9" },
      { name: "milk", quantity: "500ml" },
      { name: "cheddar cheese", quantity: "150g" },
      { name: "chopped tomatoes", quantity: "1 tin" },
      { name: "onion", quantity: "1" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "butter", quantity: "50g" },
      { name: "plain flour", quantity: "50g" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Chilli Con Carne",
    description: "Smoky beef and kidney bean chilli.",
    primaryProtein: "beef",
    isClassic: true,
    instructions: [
      "Brown 400g beef mince with onion and garlic.",
      "Add chilli powder, cumin, chopped tomatoes and kidney beans.",
      "Simmer 30 minutes, serve with rice.",
    ],
    ingredients: [
      { name: "beef mince", quantity: "400g" },
      { name: "kidney beans", quantity: "1 tin" },
      { name: "chopped tomatoes", quantity: "1 tin" },
      { name: "rice", quantity: "300g" },
      { name: "onion", quantity: "1" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "chilli powder", quantity: "2 tsp" },
      { name: "ground cumin", quantity: "1 tsp" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Beef Massaman Curry",
    description: "Rich Thai-style coconut curry with tender beef.",
    primaryProtein: "beef",
    isClassic: false,
    instructions: [
      "Brown 500g diced beef, set aside.",
      "Fry massaman paste, add coconut milk, beef and potatoes.",
      "Simmer 1.5 hours until beef is tender, serve with rice.",
    ],
    ingredients: [
      { name: "diced beef", quantity: "500g" },
      { name: "coconut milk", quantity: "400ml" },
      { name: "massaman curry paste", quantity: "3 tbsp" },
      { name: "potatoes", quantity: "300g" },
      { name: "vegetable oil", quantity: "1 tbsp" },
      { name: "rice", quantity: "300g" },
      { name: "salt", quantity: "to taste" },
    ],
  },
  {
    name: "Beef Burgers",
    description: "Homemade beef patties in brioche buns.",
    primaryProtein: "beef",
    isClassic: false,
    instructions: [
      "Shape 400g beef mince into two patties, season well.",
      "Fry or grill 4 minutes each side, add cheese to melt.",
      "Serve in toasted brioche buns with salad and sauce.",
    ],
    ingredients: [
      { name: "beef mince", quantity: "400g" },
      { name: "brioche buns", quantity: "2" },
      { name: "cheddar cheese", quantity: "2 slices" },
      { name: "lettuce", quantity: "4 leaves" },
      { name: "burger sauce", quantity: "2 tbsp" },
      { name: "vegetable oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Beef Wellington",
    description: "Fillet beef wrapped in mushroom duxelles and puff pastry.",
    primaryProtein: "beef",
    isClassic: false,
    instructions: [
      "Sear a beef fillet on all sides, cool.",
      "Wrap in mushroom duxelles, parma ham and puff pastry.",
      "Bake at 200C for 25-30 minutes, rest before slicing.",
    ],
    ingredients: [
      { name: "beef fillet", quantity: "500g" },
      { name: "puff pastry", quantity: "500g" },
      { name: "mushrooms", quantity: "300g" },
      { name: "parma ham", quantity: "6 slices" },
      { name: "egg", quantity: "1" },
      { name: "dijon mustard", quantity: "1 tbsp" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Beef and Broccoli Noodles",
    description: "Sticky soy beef with broccoli over noodles.",
    primaryProtein: "beef",
    isClassic: false,
    instructions: [
      "Marinate 350g sliced beef in soy, cornflour and ginger.",
      "Fry beef until browned, add broccoli and a sticky soy sauce.",
      "Toss with cooked noodles.",
    ],
    ingredients: [
      { name: "beef strips", quantity: "350g" },
      { name: "broccoli", quantity: "250g" },
      { name: "noodles", quantity: "250g" },
      { name: "soy sauce", quantity: "4 tbsp" },
      { name: "cornflour", quantity: "1 tbsp" },
      { name: "ginger", quantity: "20g" },
      { name: "vegetable oil", quantity: "2 tbsp" },
    ],
  },

  // --- Chicken ---
  {
    name: "Chicken Tikka Masala",
    description: "Creamy spiced curry with grilled chicken.",
    primaryProtein: "chicken",
    isClassic: true,
    instructions: [
      "Marinate 500g diced chicken thigh in yoghurt and tikka spices for 30 minutes.",
      "Grill or pan-fry until charred and cooked through.",
      "Make a sauce with onion, garlic, ginger, tinned tomatoes and cream.",
      "Combine chicken with sauce, simmer 10 minutes, serve with rice and naan.",
    ],
    ingredients: [
      { name: "chicken thighs", quantity: "500g" },
      { name: "natural yoghurt", quantity: "150g" },
      { name: "chopped tomatoes", quantity: "1 tin" },
      { name: "double cream", quantity: "100ml" },
      { name: "basmati rice", quantity: "300g" },
      { name: "onion", quantity: "1" },
      { name: "garlic", quantity: "3 cloves" },
      { name: "ginger", quantity: "20g" },
      { name: "tikka masala spice mix", quantity: "2 tbsp" },
      { name: "naan bread", quantity: "2" },
      { name: "vegetable oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Sunday Roast Chicken",
    description: "Whole roast chicken with all the trimmings.",
    primaryProtein: "chicken",
    isClassic: true,
    instructions: [
      "Roast a whole chicken at 200C for around 90 minutes.",
      "Roast potatoes in the fat for the last hour.",
      "Steam carrots and greens, make gravy from the pan juices.",
      "Carve and serve.",
    ],
    ingredients: [
      { name: "whole chicken", quantity: "1.5kg" },
      { name: "potatoes", quantity: "1kg" },
      { name: "carrots", quantity: "4" },
      { name: "chicken stock", quantity: "300ml" },
      { name: "greens", quantity: "300g" },
      { name: "vegetable oil", quantity: "2 tbsp" },
      { name: "plain flour", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Chicken Fajitas",
    description: "Sizzling chicken and peppers with warm tortillas.",
    primaryProtein: "chicken",
    isClassic: true,
    instructions: [
      "Slice 400g chicken breast and mixed peppers.",
      "Fry with fajita seasoning until chicken is cooked through.",
      "Serve with warm tortillas, soured cream and guacamole.",
    ],
    ingredients: [
      { name: "chicken breast", quantity: "400g" },
      { name: "mixed peppers", quantity: "3" },
      { name: "tortilla wraps", quantity: "6" },
      { name: "soured cream", quantity: "150g" },
      { name: "fajita seasoning", quantity: "1 packet" },
      { name: "guacamole", quantity: "150g" },
      { name: "vegetable oil", quantity: "1 tbsp" },
    ],
  },
  {
    name: "Chicken Katsu Curry",
    description: "Crispy breaded chicken with a mild curry sauce.",
    primaryProtein: "chicken",
    isClassic: false,
    instructions: [
      "Coat two chicken breasts in flour, egg and panko breadcrumbs.",
      "Fry until golden and cooked through, slice.",
      "Make a curry sauce with onion, curry powder, flour and stock.",
      "Serve chicken over rice with the sauce.",
    ],
    ingredients: [
      { name: "chicken breast", quantity: "2" },
      { name: "panko breadcrumbs", quantity: "100g" },
      { name: "curry powder", quantity: "2 tbsp" },
      { name: "rice", quantity: "300g" },
      { name: "plain flour", quantity: "50g" },
      { name: "eggs", quantity: "1" },
      { name: "onion", quantity: "1" },
      { name: "chicken stock", quantity: "300ml" },
      { name: "vegetable oil", quantity: "2 tbsp" },
    ],
  },
  {
    name: "Lemon Chicken Traybake",
    description: "One-tray roasted chicken thighs with lemon and potatoes.",
    primaryProtein: "chicken",
    isClassic: false,
    instructions: [
      "Toss chicken thighs, halved potatoes and lemon wedges in oil and herbs.",
      "Roast at 200C for 40-45 minutes until golden.",
      "Serve with the pan juices spooned over.",
    ],
    ingredients: [
      { name: "chicken thighs", quantity: "6" },
      { name: "potatoes", quantity: "500g" },
      { name: "lemon", quantity: "1" },
      { name: "mixed herbs", quantity: "1 tbsp" },
      { name: "olive oil", quantity: "3 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Chicken Caesar Salad",
    description: "Grilled chicken over crisp lettuce with Caesar dressing.",
    primaryProtein: "chicken",
    isClassic: false,
    instructions: [
      "Grill two seasoned chicken breasts, slice.",
      "Toss romaine lettuce with Caesar dressing, croutons and parmesan.",
      "Top with sliced chicken.",
    ],
    ingredients: [
      { name: "chicken breast", quantity: "2" },
      { name: "romaine lettuce", quantity: "1" },
      { name: "parmesan", quantity: "50g" },
      { name: "croutons", quantity: "80g" },
      { name: "caesar dressing", quantity: "80ml" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Peri Peri Chicken",
    description: "Spicy grilled chicken with a peri peri glaze.",
    primaryProtein: "chicken",
    isClassic: false,
    instructions: [
      "Marinate chicken thighs in peri peri sauce for at least 20 minutes.",
      "Grill or bake until charred and cooked through.",
      "Serve with corn on the cob and spicy rice.",
    ],
    ingredients: [
      { name: "chicken thighs", quantity: "6" },
      { name: "peri peri sauce", quantity: "100ml" },
      { name: "corn on the cob", quantity: "2" },
      { name: "rice", quantity: "250g" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Chicken Noodle Soup",
    description: "Comforting broth with chicken, noodles and vegetables.",
    primaryProtein: "chicken",
    isClassic: false,
    instructions: [
      "Simmer chicken thighs in stock with carrot and celery until cooked.",
      "Shred the chicken, return to the pot with noodles.",
      "Simmer until noodles are tender, season and serve.",
    ],
    ingredients: [
      { name: "chicken thighs", quantity: "300g" },
      { name: "chicken stock", quantity: "1.2L" },
      { name: "egg noodles", quantity: "150g" },
      { name: "carrots", quantity: "2" },
      { name: "celery", quantity: "2 sticks" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "BBQ Pulled Chicken",
    description: "Slow-cooked shredded chicken in smoky BBQ sauce.",
    primaryProtein: "chicken",
    isClassic: false,
    instructions: [
      "Slow-cook chicken thighs with BBQ sauce and stock for 3-4 hours.",
      "Shred the chicken and mix back through the sauce.",
      "Serve in brioche buns with coleslaw.",
    ],
    ingredients: [
      { name: "chicken thighs", quantity: "600g" },
      { name: "BBQ sauce", quantity: "200ml" },
      { name: "brioche buns", quantity: "2" },
      { name: "coleslaw", quantity: "150g" },
      { name: "chicken stock", quantity: "200ml" },
    ],
  },
  {
    name: "Chicken Fried Rice",
    description: "Quick fried rice with chicken, egg and vegetables.",
    primaryProtein: "chicken",
    isClassic: false,
    instructions: [
      "Fry diced chicken until cooked, set aside.",
      "Scramble an egg in the same pan, add cooked rice and vegetables.",
      "Combine with chicken and soy sauce, stir fry until hot.",
    ],
    ingredients: [
      { name: "chicken breast", quantity: "300g" },
      { name: "cooked rice", quantity: "400g" },
      { name: "frozen peas and carrots", quantity: "150g" },
      { name: "eggs", quantity: "2" },
      { name: "soy sauce", quantity: "2 tbsp" },
      { name: "vegetable oil", quantity: "2 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Coq au Vin",
    description: "French braised chicken in red wine with mushrooms and bacon.",
    primaryProtein: "chicken",
    isClassic: false,
    instructions: [
      "Brown chicken thighs and lardons in a casserole.",
      "Add shallots, mushrooms, red wine and stock.",
      "Cover and simmer 45 minutes until chicken is tender.",
    ],
    ingredients: [
      { name: "chicken thighs", quantity: "6" },
      { name: "bacon lardons", quantity: "150g" },
      { name: "red wine", quantity: "300ml" },
      { name: "chestnut mushrooms", quantity: "200g" },
      { name: "shallots", quantity: "150g" },
      { name: "chicken stock", quantity: "200ml" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Honey Garlic Chicken Thighs",
    description: "Sticky honey garlic glazed chicken thighs.",
    primaryProtein: "chicken",
    isClassic: false,
    instructions: [
      "Sear chicken thighs skin-side down until golden.",
      "Add honey, soy sauce and garlic, simmer until sticky and cooked through.",
      "Serve with rice and greens.",
    ],
    ingredients: [
      { name: "chicken thighs", quantity: "6" },
      { name: "honey", quantity: "3 tbsp" },
      { name: "soy sauce", quantity: "3 tbsp" },
      { name: "garlic", quantity: "3 cloves" },
      { name: "rice", quantity: "300g" },
      { name: "greens", quantity: "200g" },
      { name: "vegetable oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },

  // --- Pork ---
  {
    name: "Sausage and Mash",
    description: "Pork sausages with creamy mash and onion gravy.",
    primaryProtein: "pork",
    isClassic: true,
    instructions: [
      "Grill or fry 6 pork sausages until browned and cooked through.",
      "Boil and mash potatoes with butter and milk.",
      "Make onion gravy, serve together.",
    ],
    ingredients: [
      { name: "pork sausages", quantity: "6" },
      { name: "potatoes", quantity: "700g" },
      { name: "onion", quantity: "1" },
      { name: "beef stock", quantity: "300ml" },
      { name: "butter", quantity: "40g" },
      { name: "milk", quantity: "100ml" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Pulled Pork Buns",
    description: "Slow-cooked shredded pork shoulder in barbecue buns.",
    primaryProtein: "pork",
    isClassic: false,
    instructions: [
      "Slow-cook pork shoulder with BBQ rub for 4-5 hours until tender.",
      "Shred the pork and mix with BBQ sauce.",
      "Serve in brioche buns with slaw.",
    ],
    ingredients: [
      { name: "pork shoulder", quantity: "700g" },
      { name: "BBQ sauce", quantity: "200ml" },
      { name: "brioche buns", quantity: "2" },
      { name: "coleslaw", quantity: "150g" },
      { name: "BBQ spice rub", quantity: "2 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Pork Belly Bao",
    description: "Steamed bao buns filled with crispy pork belly.",
    primaryProtein: "pork",
    isClassic: false,
    instructions: [
      "Roast pork belly slices until crispy.",
      "Steam bao buns according to packet instructions.",
      "Fill buns with pork, pickled cucumber and hoisin sauce.",
    ],
    ingredients: [
      { name: "pork belly slices", quantity: "400g" },
      { name: "bao buns", quantity: "6" },
      { name: "hoisin sauce", quantity: "4 tbsp" },
      { name: "cucumber", quantity: "1" },
      { name: "salt", quantity: "1 tsp" },
    ],
  },
  {
    name: "Sweet and Sour Pork",
    description: "Crispy pork with pineapple in a tangy sauce.",
    primaryProtein: "pork",
    isClassic: false,
    instructions: [
      "Coat diced pork loin in cornflour and fry until crisp.",
      "Stir fry peppers and pineapple, add sweet and sour sauce.",
      "Combine with pork, serve with rice.",
    ],
    ingredients: [
      { name: "pork loin", quantity: "400g" },
      { name: "tinned pineapple", quantity: "1 tin" },
      { name: "mixed peppers", quantity: "2" },
      { name: "rice", quantity: "300g" },
      { name: "cornflour", quantity: "3 tbsp" },
      { name: "sweet and sour sauce", quantity: "200ml" },
      { name: "vegetable oil", quantity: "3 tbsp" },
    ],
  },
  {
    name: "Toad in the Hole",
    description: "Pork sausages baked in a golden Yorkshire pudding batter.",
    primaryProtein: "pork",
    isClassic: true,
    instructions: [
      "Brown 6 sausages in a hot ovenproof pan with oil.",
      "Pour over a batter of flour, eggs and milk.",
      "Bake at 220C for 25-30 minutes until risen and golden.",
    ],
    ingredients: [
      { name: "pork sausages", quantity: "6" },
      { name: "plain flour", quantity: "140g" },
      { name: "eggs", quantity: "4" },
      { name: "milk", quantity: "200ml" },
      { name: "vegetable oil", quantity: "2 tbsp" },
      { name: "salt", quantity: "1 tsp" },
    ],
  },
  {
    name: "Pork Chops with Apple Sauce",
    description: "Pan-fried pork chops with a classic apple sauce.",
    primaryProtein: "pork",
    isClassic: false,
    instructions: [
      "Season and pan-fry two pork chops until cooked through.",
      "Simmer chopped apple with a little sugar and water until soft.",
      "Serve chops with apple sauce and greens.",
    ],
    ingredients: [
      { name: "pork chops", quantity: "2" },
      { name: "cooking apples", quantity: "2" },
      { name: "green beans", quantity: "200g" },
      { name: "sugar", quantity: "1 tbsp" },
      { name: "vegetable oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Chorizo and Bean Stew",
    description: "Smoky chorizo simmered with butter beans and tomatoes.",
    primaryProtein: "pork",
    isClassic: false,
    instructions: [
      "Fry sliced chorizo until it releases its oils.",
      "Add onion, garlic, chopped tomatoes and butter beans.",
      "Simmer 20 minutes, serve with crusty bread.",
    ],
    ingredients: [
      { name: "chorizo", quantity: "200g" },
      { name: "butter beans", quantity: "1 tin" },
      { name: "chopped tomatoes", quantity: "1 tin" },
      { name: "onion", quantity: "1" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Pork Katsu Curry",
    description: "Crispy breaded pork loin with a mild curry sauce.",
    primaryProtein: "pork",
    isClassic: false,
    instructions: [
      "Coat pork loin steaks in flour, egg and panko breadcrumbs.",
      "Fry until golden and cooked through, slice.",
      "Serve over rice with a curry sauce.",
    ],
    ingredients: [
      { name: "pork loin steaks", quantity: "2" },
      { name: "panko breadcrumbs", quantity: "100g" },
      { name: "curry powder", quantity: "2 tbsp" },
      { name: "rice", quantity: "300g" },
      { name: "plain flour", quantity: "50g" },
      { name: "eggs", quantity: "1" },
      { name: "onion", quantity: "1" },
      { name: "chicken stock", quantity: "300ml" },
      { name: "vegetable oil", quantity: "2 tbsp" },
    ],
  },
  {
    name: "Bacon Carbonara",
    description: "Creamy pasta with crispy bacon, egg and parmesan.",
    primaryProtein: "pork",
    isClassic: false,
    instructions: [
      "Cook 300g spaghetti until al dente.",
      "Fry bacon lardons until crisp.",
      "Off the heat, toss pasta with bacon, beaten egg and parmesan to create a creamy sauce.",
    ],
    ingredients: [
      { name: "spaghetti", quantity: "300g" },
      { name: "bacon lardons", quantity: "150g" },
      { name: "eggs", quantity: "3" },
      { name: "parmesan", quantity: "80g" },
      { name: "black pepper", quantity: "1 tsp" },
      { name: "salt", quantity: "to taste" },
    ],
  },
  {
    name: "Honey Mustard Pork Tenderloin",
    description: "Roasted pork tenderloin glazed with honey and mustard.",
    primaryProtein: "pork",
    isClassic: false,
    instructions: [
      "Sear a pork tenderloin on all sides.",
      "Brush with honey mustard glaze, roast at 200C for 20 minutes.",
      "Rest, slice and serve with roasted vegetables.",
    ],
    ingredients: [
      { name: "pork tenderloin", quantity: "500g" },
      { name: "honey", quantity: "2 tbsp" },
      { name: "dijon mustard", quantity: "2 tbsp" },
      { name: "mixed vegetables", quantity: "400g" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },

  // --- Lamb ---
  {
    name: "Lamb Kofta with Flatbread",
    description: "Spiced lamb koftas with flatbread and yoghurt sauce.",
    primaryProtein: "lamb",
    isClassic: true,
    instructions: [
      "Mix lamb mince with cumin, coriander and garlic, shape into koftas.",
      "Grill or fry until cooked through.",
      "Serve in warm flatbreads with yoghurt sauce and salad.",
    ],
    ingredients: [
      { name: "lamb mince", quantity: "400g" },
      { name: "flatbreads", quantity: "4" },
      { name: "natural yoghurt", quantity: "150g" },
      { name: "cucumber", quantity: "1" },
      { name: "ground cumin", quantity: "1 tsp" },
      { name: "ground coriander", quantity: "1 tsp" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "mixed salad", quantity: "100g" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Shepherd's Pie",
    description: "Lamb mince in gravy topped with creamy mashed potato.",
    primaryProtein: "lamb",
    isClassic: true,
    instructions: [
      "Brown 400g lamb mince with onion and carrot.",
      "Add stock and Worcestershire sauce, simmer 20 minutes.",
      "Top with mashed potato and bake at 200C for 20 minutes.",
    ],
    ingredients: [
      { name: "lamb mince", quantity: "400g" },
      { name: "potatoes", quantity: "700g" },
      { name: "lamb stock", quantity: "300ml" },
      { name: "carrots", quantity: "2" },
      { name: "onion", quantity: "1" },
      { name: "worcestershire sauce", quantity: "1 tbsp" },
      { name: "butter", quantity: "40g" },
      { name: "milk", quantity: "100ml" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Lamb Rogan Josh",
    description: "Slow-cooked lamb curry in a rich tomato and spice sauce.",
    primaryProtein: "lamb",
    isClassic: false,
    instructions: [
      "Brown 500g diced lamb shoulder, set aside.",
      "Fry onion, garlic, ginger and rogan josh spices.",
      "Return lamb with chopped tomatoes, simmer 1.5 hours until tender.",
    ],
    ingredients: [
      { name: "diced lamb shoulder", quantity: "500g" },
      { name: "chopped tomatoes", quantity: "1 tin" },
      { name: "rogan josh curry paste", quantity: "3 tbsp" },
      { name: "rice", quantity: "300g" },
      { name: "onion", quantity: "1" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "ginger", quantity: "20g" },
      { name: "vegetable oil", quantity: "1 tbsp" },
      { name: "salt", quantity: "to taste" },
    ],
  },
  {
    name: "Slow Roast Lamb Shoulder",
    description: "Melt-in-the-mouth lamb shoulder roasted low and slow.",
    primaryProtein: "lamb",
    isClassic: false,
    instructions: [
      "Rub a lamb shoulder with garlic, rosemary and oil.",
      "Roast at 150C for 4-5 hours until falling apart.",
      "Rest, shred and serve with roasted vegetables.",
    ],
    ingredients: [
      { name: "lamb shoulder", quantity: "1.5kg" },
      { name: "garlic", quantity: "1 bulb" },
      { name: "rosemary", quantity: "4 sprigs" },
      { name: "potatoes", quantity: "600g" },
      { name: "olive oil", quantity: "2 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Lamb Koftas Curry",
    description: "Lamb koftas simmered in a spiced curry sauce.",
    primaryProtein: "lamb",
    isClassic: false,
    instructions: [
      "Shape spiced lamb mince into koftas, fry until browned.",
      "Make a curry sauce with onion, garlic and tomatoes.",
      "Simmer koftas in the sauce for 15 minutes, serve with rice.",
    ],
    ingredients: [
      { name: "lamb mince", quantity: "400g" },
      { name: "chopped tomatoes", quantity: "1 tin" },
      { name: "curry powder", quantity: "2 tbsp" },
      { name: "rice", quantity: "300g" },
      { name: "onion", quantity: "1" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "ground cumin", quantity: "1 tsp" },
      { name: "vegetable oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Greek Lamb Souvlaki",
    description: "Grilled marinated lamb skewers with pitta and tzatziki.",
    primaryProtein: "lamb",
    isClassic: false,
    instructions: [
      "Marinate cubed lamb leg in lemon, garlic and oregano.",
      "Skewer and grill until charred and cooked through.",
      "Serve with warm pitta, tzatziki and salad.",
    ],
    ingredients: [
      { name: "lamb leg", quantity: "400g" },
      { name: "pitta bread", quantity: "4" },
      { name: "tzatziki", quantity: "150g" },
      { name: "lemon", quantity: "1" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "oregano", quantity: "1 tbsp" },
      { name: "olive oil", quantity: "2 tbsp" },
      { name: "mixed salad", quantity: "100g" },
    ],
  },
  {
    name: "Lamb and Mint Burgers",
    description: "Juicy lamb patties with fresh mint and feta.",
    primaryProtein: "lamb",
    isClassic: false,
    instructions: [
      "Mix lamb mince with chopped mint, garlic and crumbled feta.",
      "Shape into patties and grill or fry until cooked through.",
      "Serve in buns with salad and yoghurt sauce.",
    ],
    ingredients: [
      { name: "lamb mince", quantity: "400g" },
      { name: "feta cheese", quantity: "80g" },
      { name: "mint", quantity: "1 handful" },
      { name: "burger buns", quantity: "2" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "natural yoghurt", quantity: "100g" },
      { name: "mixed salad", quantity: "100g" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Moroccan Lamb Tagine",
    description: "Fragrant slow-cooked lamb with apricots and spices.",
    primaryProtein: "lamb",
    isClassic: false,
    instructions: [
      "Brown diced lamb shoulder with onion and Moroccan spices.",
      "Add stock, dried apricots and chickpeas.",
      "Simmer covered for 1.5-2 hours until tender, serve with couscous.",
    ],
    ingredients: [
      { name: "diced lamb shoulder", quantity: "500g" },
      { name: "dried apricots", quantity: "100g" },
      { name: "chickpeas", quantity: "1 tin" },
      { name: "couscous", quantity: "250g" },
      { name: "onion", quantity: "1" },
      { name: "lamb stock", quantity: "400ml" },
      { name: "ground cumin", quantity: "1 tsp" },
      { name: "ground cinnamon", quantity: "1 tsp" },
      { name: "ground ginger", quantity: "1 tsp" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },

  // --- A few others, for protein-rotation variety ---
  {
    name: "Veggie Chilli",
    description: "Hearty bean and lentil chilli.",
    primaryProtein: "lentils",
    isClassic: true,
    instructions: [
      "Fry onion, pepper and garlic until soft.",
      "Add chilli powder, cumin, tinned tomatoes, kidney beans and lentils.",
      "Simmer 25 minutes, season to taste, serve with rice.",
    ],
    ingredients: [
      { name: "kidney beans", quantity: "1 tin" },
      { name: "red lentils", quantity: "150g" },
      { name: "chopped tomatoes", quantity: "1 tin" },
      { name: "bell pepper", quantity: "1" },
      { name: "onion", quantity: "1" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "chilli powder", quantity: "1 tbsp" },
      { name: "ground cumin", quantity: "1 tsp" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "rice", quantity: "300g" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Fish and Chips",
    description: "Beer-battered fish with chunky chips.",
    primaryProtein: "fish",
    isClassic: true,
    instructions: [
      "Cut potatoes into chips, parboil, then roast or fry until golden.",
      "Make a beer batter and coat two fish fillets.",
      "Fry fish until golden and cooked through, serve with peas.",
    ],
    ingredients: [
      { name: "white fish fillets", quantity: "2" },
      { name: "potatoes", quantity: "800g" },
      { name: "plain flour", quantity: "150g" },
      { name: "beer", quantity: "200ml" },
      { name: "frozen peas", quantity: "200g" },
      { name: "vegetable oil", quantity: "500ml" },
      { name: "salt", quantity: "to taste" },
    ],
  },
  {
    name: "Salmon Teriyaki",
    description: "Pan-glazed salmon fillets with a sticky teriyaki sauce.",
    primaryProtein: "fish",
    isClassic: false,
    instructions: [
      "Pan-fry two salmon fillets skin-side down until crisp.",
      "Add teriyaki sauce, glaze the salmon as it finishes cooking.",
      "Serve with rice and steamed greens.",
    ],
    ingredients: [
      { name: "salmon fillets", quantity: "2" },
      { name: "teriyaki sauce", quantity: "80ml" },
      { name: "rice", quantity: "250g" },
      { name: "pak choi", quantity: "2" },
      { name: "vegetable oil", quantity: "1 tbsp" },
    ],
  },
  {
    name: "Prawn Linguine",
    description: "Garlicky prawns tossed with linguine and chilli.",
    primaryProtein: "prawns",
    isClassic: false,
    instructions: [
      "Cook 250g linguine until al dente.",
      "Fry king prawns with garlic, chilli and butter.",
      "Toss with pasta, a splash of pasta water and parsley.",
    ],
    ingredients: [
      { name: "linguine", quantity: "250g" },
      { name: "king prawns", quantity: "300g" },
      { name: "garlic", quantity: "3 cloves" },
      { name: "chilli flakes", quantity: "1 tsp" },
      { name: "butter", quantity: "40g" },
      { name: "flat leaf parsley", quantity: "1 handful" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Turkey Meatballs",
    description: "Lean turkey meatballs in a tomato sauce.",
    primaryProtein: "turkey",
    isClassic: false,
    instructions: [
      "Shape turkey mince with breadcrumbs and herbs into meatballs.",
      "Fry until browned, then simmer in tomato sauce for 15 minutes.",
      "Serve with spaghetti or crusty bread.",
    ],
    ingredients: [
      { name: "turkey mince", quantity: "400g" },
      { name: "chopped tomatoes", quantity: "1 tin" },
      { name: "breadcrumbs", quantity: "50g" },
      { name: "spaghetti", quantity: "250g" },
      { name: "mixed herbs", quantity: "1 tbsp" },
      { name: "egg", quantity: "1" },
      { name: "vegetable oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Tofu Stir Fry",
    description: "Quick veg and tofu stir fry with soy-ginger sauce.",
    primaryProtein: "tofu",
    isClassic: false,
    instructions: [
      "Press and cube 400g firm tofu, fry until golden.",
      "Stir fry mixed vegetables in a hot wok.",
      "Add soy sauce, ginger, garlic and a splash of sesame oil, combine with tofu and noodles.",
    ],
    ingredients: [
      { name: "firm tofu", quantity: "400g" },
      { name: "mixed stir fry vegetables", quantity: "300g" },
      { name: "noodles", quantity: "250g" },
      { name: "soy sauce", quantity: "3 tbsp" },
      { name: "ginger", quantity: "20g" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "sesame oil", quantity: "1 tbsp" },
      { name: "vegetable oil", quantity: "2 tbsp" },
    ],
  },
  {
    name: "Halloumi Buddha Bowl",
    description: "Grilled halloumi with roasted vegetables and grains.",
    primaryProtein: "halloumi",
    isClassic: false,
    instructions: [
      "Roast mixed vegetables at 200C for 25 minutes.",
      "Grill sliced halloumi until golden.",
      "Serve over cooked grains with a drizzle of tahini dressing.",
    ],
    ingredients: [
      { name: "halloumi", quantity: "225g" },
      { name: "mixed vegetables", quantity: "400g" },
      { name: "couscous", quantity: "200g" },
      { name: "tahini", quantity: "2 tbsp" },
      { name: "olive oil", quantity: "2 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Mushroom Risotto",
    description: "Creamy arborio rice with mushrooms and parmesan.",
    primaryProtein: "mushroom",
    isClassic: false,
    instructions: [
      "Fry mushrooms and onion, set mushrooms aside.",
      "Toast arborio rice, gradually add hot stock, stirring until creamy.",
      "Stir through mushrooms and parmesan, season and serve.",
    ],
    ingredients: [
      { name: "arborio rice", quantity: "250g" },
      { name: "chestnut mushrooms", quantity: "300g" },
      { name: "vegetable stock", quantity: "1L" },
      { name: "parmesan", quantity: "60g" },
      { name: "onion", quantity: "1" },
      { name: "butter", quantity: "40g" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },

  // --- Beef, round two: more adventurous ---
  {
    name: "Korean Beef Bulgogi",
    description: "Sweet-savoury marinated beef, seared fast and served over rice.",
    primaryProtein: "beef",
    isClassic: false,
    instructions: [
      "Marinate thinly sliced beef sirloin in soy, pear or apple, garlic, ginger and sesame oil for 30 minutes.",
      "Sear in a very hot pan or wok in batches until caramelised at the edges.",
      "Serve over rice with pickled vegetables and a fried egg.",
    ],
    ingredients: [
      { name: "beef sirloin", quantity: "400g" },
      { name: "soy sauce", quantity: "4 tbsp" },
      { name: "sesame oil", quantity: "1 tbsp" },
      { name: "rice", quantity: "300g" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "ginger", quantity: "20g" },
      { name: "apple", quantity: "1" },
      { name: "eggs", quantity: "2" },
      { name: "pickled vegetables", quantity: "150g" },
      { name: "vegetable oil", quantity: "1 tbsp" },
    ],
  },
  {
    name: "Beef Rendang",
    description: "Indonesian slow-cooked beef in a deeply spiced coconut sauce.",
    primaryProtein: "beef",
    isClassic: false,
    instructions: [
      "Blend lemongrass, shallots, garlic, chilli and galangal into a paste.",
      "Fry the paste, add diced beef shin, coconut milk and kaffir lime leaves.",
      "Simmer uncovered for 2+ hours, stirring occasionally, until dark and thick.",
    ],
    ingredients: [
      { name: "diced beef shin", quantity: "500g" },
      { name: "coconut milk", quantity: "400ml" },
      { name: "lemongrass", quantity: "2 stalks" },
      { name: "rice", quantity: "300g" },
      { name: "shallots", quantity: "100g" },
      { name: "garlic", quantity: "3 cloves" },
      { name: "red chilli", quantity: "2" },
      { name: "galangal", quantity: "20g" },
      { name: "kaffir lime leaves", quantity: "4" },
      { name: "vegetable oil", quantity: "2 tbsp" },
    ],
  },
  {
    name: "Vietnamese Beef Pho",
    description: "Fragrant beef noodle soup with star anise and fresh herbs.",
    primaryProtein: "beef",
    isClassic: false,
    instructions: [
      "Simmer beef stock with charred onion, ginger, star anise and cinnamon for 30 minutes.",
      "Cook rice noodles and thinly slice raw beef sirloin.",
      "Assemble bowls: noodles, raw beef (cooked by the hot broth), pour over broth, top with herbs and beansprouts.",
    ],
    ingredients: [
      { name: "beef sirloin", quantity: "250g" },
      { name: "beef stock", quantity: "1.2L" },
      { name: "rice noodles", quantity: "250g" },
      { name: "beansprouts", quantity: "150g" },
      { name: "onion", quantity: "1" },
      { name: "ginger", quantity: "40g" },
      { name: "star anise", quantity: "3" },
      { name: "cinnamon stick", quantity: "1" },
      { name: "fresh coriander", quantity: "1 handful" },
    ],
  },
  {
    name: "Beef Bourguignon",
    description: "Classic French braise of beef in red wine with bacon and pearl onions.",
    primaryProtein: "beef",
    isClassic: false,
    instructions: [
      "Brown diced beef chuck in batches, set aside.",
      "Fry bacon lardons and pearl onions, add mushrooms and garlic.",
      "Return beef with red wine and stock, simmer covered 2.5 hours until tender.",
    ],
    ingredients: [
      { name: "diced beef chuck", quantity: "500g" },
      { name: "red wine", quantity: "400ml" },
      { name: "bacon lardons", quantity: "120g" },
      { name: "pearl onions", quantity: "150g" },
      { name: "chestnut mushrooms", quantity: "200g" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "beef stock", quantity: "300ml" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Thai Beef Salad",
    description: "Zesty seared beef salad with lime, chilli and fresh herbs.",
    primaryProtein: "beef",
    isClassic: false,
    instructions: [
      "Sear a sirloin steak to medium-rare, rest and slice thinly.",
      "Whisk lime juice, fish sauce, sugar and chilli for the dressing.",
      "Toss beef with salad leaves, cucumber, red onion and herbs, dress and serve.",
    ],
    ingredients: [
      { name: "beef sirloin", quantity: "350g" },
      { name: "lime", quantity: "2" },
      { name: "fish sauce", quantity: "2 tbsp" },
      { name: "mixed salad leaves", quantity: "150g" },
      { name: "sugar", quantity: "1 tbsp" },
      { name: "red chilli", quantity: "1" },
      { name: "cucumber", quantity: "0.5" },
      { name: "red onion", quantity: "0.5" },
      { name: "fresh mint", quantity: "1 handful" },
      { name: "fresh coriander", quantity: "1 handful" },
    ],
  },
  {
    name: "Beef Yakiniku Skewers",
    description: "Japanese-style grilled beef skewers with a sweet soy glaze.",
    primaryProtein: "beef",
    isClassic: false,
    instructions: [
      "Cube beef sirloin and thread onto skewers with spring onion.",
      "Marinate briefly in soy, mirin, sake and sugar.",
      "Grill hot and fast, basting with the glaze, serve with rice.",
    ],
    ingredients: [
      { name: "beef sirloin", quantity: "400g" },
      { name: "soy sauce", quantity: "3 tbsp" },
      { name: "mirin", quantity: "2 tbsp" },
      { name: "spring onion", quantity: "4" },
      { name: "sake", quantity: "2 tbsp" },
      { name: "sugar", quantity: "1 tbsp" },
      { name: "rice", quantity: "300g" },
    ],
  },

  // --- Chicken, round two ---
  {
    name: "Chicken Shawarma",
    description: "Spiced chicken thighs, charred and wrapped with garlic sauce.",
    primaryProtein: "chicken",
    isClassic: false,
    instructions: [
      "Marinate chicken thighs in shawarma spices, yoghurt, garlic and lemon.",
      "Roast or grill until charred and cooked through, slice.",
      "Serve in flatbreads with garlic sauce, pickles and salad.",
    ],
    ingredients: [
      { name: "chicken thighs", quantity: "500g" },
      { name: "natural yoghurt", quantity: "100g" },
      { name: "flatbreads", quantity: "4" },
      { name: "garlic", quantity: "3 cloves" },
      { name: "shawarma spice mix", quantity: "2 tbsp" },
      { name: "lemon", quantity: "1" },
      { name: "garlic sauce", quantity: "3 tbsp" },
      { name: "pickles", quantity: "50g" },
      { name: "mixed salad", quantity: "100g" },
    ],
  },
  {
    name: "Thai Green Chicken Curry",
    description: "Fragrant coconut curry with chicken, aubergine and Thai basil.",
    primaryProtein: "chicken",
    isClassic: false,
    instructions: [
      "Fry green curry paste until fragrant.",
      "Add coconut milk, sliced chicken thigh and aubergine, simmer 15 minutes.",
      "Stir through Thai basil and serve with jasmine rice.",
    ],
    ingredients: [
      { name: "chicken thighs", quantity: "450g" },
      { name: "coconut milk", quantity: "400ml" },
      { name: "green curry paste", quantity: "3 tbsp" },
      { name: "aubergine", quantity: "1" },
      { name: "thai basil", quantity: "1 handful" },
      { name: "jasmine rice", quantity: "300g" },
      { name: "vegetable oil", quantity: "1 tbsp" },
    ],
  },
  {
    name: "Jerk Chicken",
    description: "Caribbean spiced chicken with a fiery, fragrant marinade.",
    primaryProtein: "chicken",
    isClassic: false,
    instructions: [
      "Blend scotch bonnet, allspice, thyme, garlic and lime for the marinade.",
      "Marinate chicken thighs for at least an hour, ideally overnight.",
      "Grill or bake until charred and cooked through, serve with rice and peas.",
    ],
    ingredients: [
      { name: "chicken thighs", quantity: "6" },
      { name: "scotch bonnet", quantity: "1" },
      { name: "allspice", quantity: "2 tsp" },
      { name: "rice and peas", quantity: "300g" },
      { name: "thyme", quantity: "4 sprigs" },
      { name: "garlic", quantity: "3 cloves" },
      { name: "lime", quantity: "1" },
      { name: "vegetable oil", quantity: "1 tbsp" },
    ],
  },
  {
    name: "Chicken Adobo",
    description: "Filipino braised chicken in soy, vinegar and garlic.",
    primaryProtein: "chicken",
    isClassic: false,
    instructions: [
      "Combine chicken thighs, soy sauce, vinegar, garlic and bay leaves in a pot.",
      "Simmer 30-40 minutes until chicken is tender and sauce has reduced.",
      "Serve with steamed rice.",
    ],
    ingredients: [
      { name: "chicken thighs", quantity: "600g" },
      { name: "soy sauce", quantity: "80ml" },
      { name: "white vinegar", quantity: "60ml" },
      { name: "rice", quantity: "300g" },
      { name: "garlic", quantity: "4 cloves" },
      { name: "bay leaves", quantity: "2" },
    ],
  },
  {
    name: "Butter Chicken",
    description: "Silky, mildly spiced tomato and butter curry.",
    primaryProtein: "chicken",
    isClassic: false,
    instructions: [
      "Marinate diced chicken thigh in yoghurt and garam masala.",
      "Grill or pan-fry until charred, set aside.",
      "Simmer tomato passata with butter, cream and spices, add chicken, finish with more butter.",
    ],
    ingredients: [
      { name: "chicken thighs", quantity: "500g" },
      { name: "tomato passata", quantity: "400ml" },
      { name: "butter", quantity: "60g" },
      { name: "double cream", quantity: "100ml" },
      { name: "natural yoghurt", quantity: "100g" },
      { name: "garam masala", quantity: "2 tbsp" },
      { name: "vegetable oil", quantity: "1 tbsp" },
      { name: "salt", quantity: "to taste" },
    ],
  },
  {
    name: "Chicken Parmigiana",
    description: "Breaded chicken breast topped with tomato sauce and melted mozzarella.",
    primaryProtein: "chicken",
    isClassic: false,
    instructions: [
      "Coat chicken breasts in flour, egg and breadcrumbs, fry until golden.",
      "Top with tomato sauce and mozzarella, bake at 200C for 10 minutes.",
      "Serve with spaghetti or a green salad.",
    ],
    ingredients: [
      { name: "chicken breast", quantity: "2" },
      { name: "mozzarella", quantity: "125g" },
      { name: "tomato passata", quantity: "300ml" },
      { name: "breadcrumbs", quantity: "100g" },
      { name: "plain flour", quantity: "50g" },
      { name: "eggs", quantity: "1" },
      { name: "vegetable oil", quantity: "2 tbsp" },
    ],
  },
  {
    name: "Hainanese Chicken Rice",
    description: "Poached chicken with fragrant rice cooked in the poaching broth.",
    primaryProtein: "chicken",
    isClassic: false,
    instructions: [
      "Gently poach a whole chicken in ginger and spring onion stock until just cooked.",
      "Cook rice in the poaching broth with garlic and ginger.",
      "Slice chicken, serve over rice with chilli-ginger sauce and cucumber.",
    ],
    ingredients: [
      { name: "whole chicken", quantity: "1.2kg" },
      { name: "rice", quantity: "300g" },
      { name: "ginger", quantity: "50g" },
      { name: "cucumber", quantity: "1" },
      { name: "spring onion", quantity: "4" },
      { name: "garlic", quantity: "3 cloves" },
      { name: "chilli-ginger sauce", quantity: "4 tbsp" },
    ],
  },
  {
    name: "Nashville Hot Chicken",
    description: "Crispy fried chicken with a fiery cayenne butter glaze.",
    primaryProtein: "chicken",
    isClassic: false,
    instructions: [
      "Marinate chicken thighs in buttermilk, then coat in seasoned flour.",
      "Fry until deeply golden and cooked through.",
      "Brush with a cayenne-spiked hot butter glaze, serve on white bread with pickles.",
    ],
    ingredients: [
      { name: "chicken thighs", quantity: "6" },
      { name: "buttermilk", quantity: "300ml" },
      { name: "cayenne pepper", quantity: "2 tbsp" },
      { name: "white bread", quantity: "4 slices" },
      { name: "plain flour", quantity: "150g" },
      { name: "butter", quantity: "60g" },
      { name: "pickles", quantity: "50g" },
      { name: "vegetable oil", quantity: "500ml" },
    ],
  },

  // --- Pork, round two ---
  {
    name: "Korean Pork Bulgogi",
    description: "Spicy-sweet gochujang pork, stir-fried fast and hot.",
    primaryProtein: "pork",
    isClassic: false,
    instructions: [
      "Marinate thinly sliced pork shoulder in gochujang, soy, garlic and sugar.",
      "Stir fry in a very hot pan until caramelised.",
      "Serve over rice with pickled vegetables.",
    ],
    ingredients: [
      { name: "pork shoulder", quantity: "400g" },
      { name: "gochujang", quantity: "3 tbsp" },
      { name: "soy sauce", quantity: "2 tbsp" },
      { name: "rice", quantity: "300g" },
      { name: "garlic", quantity: "3 cloves" },
      { name: "sugar", quantity: "1 tbsp" },
      { name: "vegetable oil", quantity: "1 tbsp" },
      { name: "pickled vegetables", quantity: "100g" },
    ],
  },
  {
    name: "Char Siu Pork",
    description: "Sticky Cantonese barbecue pork with a lacquered glaze.",
    primaryProtein: "pork",
    isClassic: false,
    instructions: [
      "Marinate pork shoulder strips in char siu sauce, honey and five spice overnight.",
      "Roast at 200C, basting regularly, until sticky and caramelised.",
      "Rest, slice and serve with rice and steamed greens.",
    ],
    ingredients: [
      { name: "pork shoulder", quantity: "500g" },
      { name: "hoisin sauce", quantity: "3 tbsp" },
      { name: "honey", quantity: "2 tbsp" },
      { name: "five spice", quantity: "1 tsp" },
      { name: "rice", quantity: "300g" },
      { name: "greens", quantity: "200g" },
    ],
  },
  {
    name: "Porchetta",
    description: "Herb and garlic stuffed rolled pork roast with crackling.",
    primaryProtein: "pork",
    isClassic: false,
    instructions: [
      "Butterfly a pork joint, stuff with garlic, rosemary, fennel seed and lemon zest.",
      "Roll and tie, score the skin well, roast at high heat then lower to finish.",
      "Rest before carving into thick slices with crisp crackling.",
    ],
    ingredients: [
      { name: "pork shoulder joint", quantity: "1.2kg" },
      { name: "garlic", quantity: "1 bulb" },
      { name: "rosemary", quantity: "4 sprigs" },
      { name: "fennel seeds", quantity: "1 tbsp" },
      { name: "lemon", quantity: "1" },
      { name: "olive oil", quantity: "2 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Cuban Mojo Pulled Pork",
    description: "Citrus and garlic marinated pork, slow-cooked until falling apart.",
    primaryProtein: "pork",
    isClassic: false,
    instructions: [
      "Marinate pork shoulder in orange juice, lime juice, garlic and cumin.",
      "Slow-cook for 4-5 hours until tender enough to shred.",
      "Shred and serve with rice and black beans.",
    ],
    ingredients: [
      { name: "pork shoulder", quantity: "700g" },
      { name: "orange juice", quantity: "200ml" },
      { name: "lime", quantity: "2" },
      { name: "black beans", quantity: "1 tin" },
      { name: "garlic", quantity: "4 cloves" },
      { name: "ground cumin", quantity: "1 tsp" },
      { name: "rice", quantity: "300g" },
    ],
  },
  {
    name: "Pork Ramen",
    description: "Rich pork broth ramen with soft egg and spring onion.",
    primaryProtein: "pork",
    isClassic: false,
    instructions: [
      "Simmer pork belly slices in a rich stock with soy, garlic and ginger for 30 minutes.",
      "Soft-boil eggs and cook ramen noodles.",
      "Assemble bowls with broth, noodles, pork, halved eggs and spring onion.",
    ],
    ingredients: [
      { name: "pork belly slices", quantity: "300g" },
      { name: "ramen noodles", quantity: "250g" },
      { name: "eggs", quantity: "2" },
      { name: "chicken stock", quantity: "1L" },
      { name: "soy sauce", quantity: "3 tbsp" },
      { name: "garlic", quantity: "3 cloves" },
      { name: "ginger", quantity: "20g" },
      { name: "spring onion", quantity: "3" },
    ],
  },

  // --- Lamb, round two ---
  {
    name: "Lamb Biryani",
    description: "Layered spiced rice and lamb, slow-cooked until fragrant.",
    primaryProtein: "lamb",
    isClassic: false,
    instructions: [
      "Marinate diced lamb shoulder in yoghurt and biryani spices.",
      "Brown the lamb, then layer with part-cooked basmati rice and fried onions.",
      "Cover and cook low until rice is fluffy and lamb is tender, then fluff and serve.",
    ],
    ingredients: [
      { name: "diced lamb shoulder", quantity: "500g" },
      { name: "basmati rice", quantity: "350g" },
      { name: "natural yoghurt", quantity: "150g" },
      { name: "fried onions", quantity: "100g" },
      { name: "biryani spice mix", quantity: "3 tbsp" },
      { name: "vegetable oil", quantity: "2 tbsp" },
      { name: "salt", quantity: "to taste" },
    ],
  },
  {
    name: "Lamb Doner Kebab",
    description: "Spiced shaved lamb in warm flatbread with salad and chilli sauce.",
    primaryProtein: "lamb",
    isClassic: false,
    instructions: [
      "Marinate thin lamb steaks in cumin, paprika and garlic.",
      "Griddle hot and fast, then slice thinly.",
      "Serve in flatbreads with salad, chilli sauce and garlic yoghurt.",
    ],
    ingredients: [
      { name: "lamb leg steaks", quantity: "400g" },
      { name: "flatbreads", quantity: "4" },
      { name: "natural yoghurt", quantity: "100g" },
      { name: "chilli sauce", quantity: "3 tbsp" },
      { name: "ground cumin", quantity: "1 tsp" },
      { name: "paprika", quantity: "1 tsp" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "mixed salad", quantity: "100g" },
    ],
  },
  {
    name: "Lamb Vindaloo",
    description: "Fiery, tangy Goan lamb curry with vinegar and chilli.",
    primaryProtein: "lamb",
    isClassic: false,
    instructions: [
      "Marinate diced lamb shoulder in vinegar, chilli and vindaloo spices.",
      "Brown the lamb, add onions, tomatoes and marinade, simmer 1.5 hours.",
      "Serve with rice and naan.",
    ],
    ingredients: [
      { name: "diced lamb shoulder", quantity: "500g" },
      { name: "malt vinegar", quantity: "4 tbsp" },
      { name: "chopped tomatoes", quantity: "1 tin" },
      { name: "rice", quantity: "300g" },
      { name: "onion", quantity: "1" },
      { name: "chilli powder", quantity: "1 tbsp" },
      { name: "vindaloo spice mix", quantity: "2 tbsp" },
      { name: "vegetable oil", quantity: "1 tbsp" },
      { name: "naan bread", quantity: "2" },
    ],
  },
  {
    name: "Lamb Navarin",
    description: "French lamb stew with baby vegetables in a rich broth.",
    primaryProtein: "lamb",
    isClassic: false,
    instructions: [
      "Brown diced lamb shoulder, set aside.",
      "Fry onion and garlic, add stock, tomato puree and lamb, simmer 1 hour.",
      "Add baby carrots and potatoes, simmer until vegetables are tender.",
    ],
    ingredients: [
      { name: "diced lamb shoulder", quantity: "500g" },
      { name: "baby carrots", quantity: "200g" },
      { name: "baby potatoes", quantity: "300g" },
      { name: "lamb stock", quantity: "500ml" },
      { name: "onion", quantity: "1" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "tomato puree", quantity: "2 tbsp" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Lamb Chops with Chimichurri",
    description: "Grilled lamb chops with a punchy herb and garlic sauce.",
    primaryProtein: "lamb",
    isClassic: false,
    instructions: [
      "Season lamb chops well and grill 3-4 minutes per side.",
      "Blend parsley, garlic, red wine vinegar, chilli and oil for the chimichurri.",
      "Rest the chops briefly, serve with chimichurri spooned over.",
    ],
    ingredients: [
      { name: "lamb chops", quantity: "6" },
      { name: "flat leaf parsley", quantity: "1 bunch" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "red wine vinegar", quantity: "2 tbsp" },
      { name: "red chilli", quantity: "1" },
      { name: "olive oil", quantity: "4 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Kleftiko",
    description: "Greek slow-roasted lamb with lemon, garlic and oregano.",
    primaryProtein: "lamb",
    isClassic: false,
    instructions: [
      "Marinate a lamb shoulder joint in lemon juice, garlic and oregano.",
      "Wrap tightly in foil with potatoes and roast low and slow for 3-4 hours.",
      "Unwrap for the final 20 minutes to brown, then serve.",
    ],
    ingredients: [
      { name: "lamb shoulder joint", quantity: "1kg" },
      { name: "lemon", quantity: "2" },
      { name: "oregano", quantity: "2 tbsp" },
      { name: "potatoes", quantity: "600g" },
      { name: "garlic", quantity: "1 bulb" },
      { name: "olive oil", quantity: "3 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },

  // --- New proteins: duck, venison, seafood, plant-based ---
  {
    name: "Crispy Duck Pancakes",
    description: "Shredded crispy duck with pancakes, cucumber and hoisin.",
    primaryProtein: "duck",
    isClassic: false,
    instructions: [
      "Rub duck legs with five spice and salt, roast slow until crisp and tender.",
      "Shred the meat, warm Chinese pancakes.",
      "Serve with hoisin sauce, cucumber and spring onion to build your own wraps.",
    ],
    ingredients: [
      { name: "duck legs", quantity: "4" },
      { name: "chinese pancakes", quantity: "12" },
      { name: "hoisin sauce", quantity: "4 tbsp" },
      { name: "cucumber", quantity: "1" },
      { name: "spring onion", quantity: "4" },
      { name: "salt", quantity: "1 tsp" },
    ],
  },
  {
    name: "Duck a l'Orange",
    description: "Pan-seared duck breast with a glossy orange sauce.",
    primaryProtein: "duck",
    isClassic: false,
    instructions: [
      "Score duck breast skin, sear skin-side down until crisp, finish in the oven.",
      "Make a sauce with orange juice, zest, stock and a touch of sugar.",
      "Rest and slice the duck, serve with the sauce.",
    ],
    ingredients: [
      { name: "duck breasts", quantity: "2" },
      { name: "oranges", quantity: "2" },
      { name: "chicken stock", quantity: "200ml" },
      { name: "potatoes", quantity: "400g" },
      { name: "sugar", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Venison Stew",
    description: "Rich, gamey venison braised with root vegetables and red wine.",
    primaryProtein: "venison",
    isClassic: false,
    instructions: [
      "Brown diced venison shoulder in batches, set aside.",
      "Fry onion, carrot and celery, add red wine, stock and juniper berries.",
      "Return venison, cover and simmer 2 hours until tender.",
    ],
    ingredients: [
      { name: "diced venison shoulder", quantity: "500g" },
      { name: "red wine", quantity: "300ml" },
      { name: "carrots", quantity: "3" },
      { name: "juniper berries", quantity: "6" },
      { name: "onion", quantity: "1" },
      { name: "celery", quantity: "2 sticks" },
      { name: "beef stock", quantity: "400ml" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Seafood Paella",
    description: "Saffron rice with prawns, mussels and chorizo.",
    primaryProtein: "seafood",
    isClassic: false,
    instructions: [
      "Fry chorizo and onion in a wide pan, add rice and saffron-infused stock.",
      "Simmer without stirring, nestling in mussels and prawns for the last 10 minutes.",
      "Rest briefly, then serve with lemon wedges.",
    ],
    ingredients: [
      { name: "paella rice", quantity: "300g" },
      { name: "king prawns", quantity: "200g" },
      { name: "mussels", quantity: "300g" },
      { name: "chorizo", quantity: "100g" },
      { name: "onion", quantity: "1" },
      { name: "saffron", quantity: "1 pinch" },
      { name: "chicken stock", quantity: "1L" },
      { name: "lemon", quantity: "1" },
      { name: "olive oil", quantity: "1 tbsp" },
    ],
  },
  {
    name: "Fish Tacos",
    description: "Crispy battered fish tacos with a zingy slaw.",
    primaryProtein: "fish",
    isClassic: false,
    instructions: [
      "Coat fish goujons in seasoned flour and fry until crisp.",
      "Toss shredded cabbage and carrot with lime juice and a little mayo for slaw.",
      "Fill warm tortillas with fish, slaw and hot sauce.",
    ],
    ingredients: [
      { name: "white fish fillets", quantity: "400g" },
      { name: "tortillas", quantity: "8" },
      { name: "red cabbage", quantity: "200g" },
      { name: "lime", quantity: "2" },
      { name: "plain flour", quantity: "100g" },
      { name: "mayonnaise", quantity: "3 tbsp" },
      { name: "hot sauce", quantity: "2 tbsp" },
      { name: "vegetable oil", quantity: "300ml" },
      { name: "carrot", quantity: "1" },
    ],
  },
  {
    name: "Miso Black Cod",
    description: "Sweet miso-marinated cod, grilled until caramelised.",
    primaryProtein: "fish",
    isClassic: false,
    instructions: [
      "Marinate cod fillets in white miso, mirin, sake and sugar for at least 2 hours.",
      "Grill or broil until caramelised and just cooked through.",
      "Serve with steamed rice and pak choi.",
    ],
    ingredients: [
      { name: "cod fillets", quantity: "2" },
      { name: "white miso paste", quantity: "3 tbsp" },
      { name: "mirin", quantity: "2 tbsp" },
      { name: "pak choi", quantity: "2" },
      { name: "sake", quantity: "2 tbsp" },
      { name: "sugar", quantity: "1 tbsp" },
      { name: "rice", quantity: "250g" },
    ],
  },
  {
    name: "Garlic Butter Scallops",
    description: "Pan-seared scallops in a garlic and herb butter sauce.",
    primaryProtein: "seafood",
    isClassic: false,
    instructions: [
      "Pat scallops dry and sear in a very hot pan, 90 seconds per side.",
      "Add butter, garlic and parsley to the pan, baste the scallops.",
      "Serve over pea puree or with crusty bread.",
    ],
    ingredients: [
      { name: "scallops", quantity: "12" },
      { name: "butter", quantity: "60g" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "frozen peas", quantity: "200g" },
      { name: "flat leaf parsley", quantity: "1 handful" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Paneer Tikka Masala",
    description: "Charred paneer in a creamy spiced tomato sauce.",
    primaryProtein: "paneer",
    isClassic: false,
    instructions: [
      "Marinate cubed paneer in yoghurt and tikka spices, grill until charred.",
      "Make a sauce with onion, garlic, tomatoes and cream.",
      "Combine paneer with sauce, simmer briefly, serve with rice or naan.",
    ],
    ingredients: [
      { name: "paneer", quantity: "225g" },
      { name: "chopped tomatoes", quantity: "1 tin" },
      { name: "double cream", quantity: "100ml" },
      { name: "naan bread", quantity: "2" },
      { name: "onion", quantity: "1" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "tikka masala spice mix", quantity: "2 tbsp" },
      { name: "vegetable oil", quantity: "1 tbsp" },
      { name: "rice", quantity: "300g" },
    ],
  },
  {
    name: "Jackfruit Curry",
    description: "Young jackfruit simmered in a warming coconut curry sauce.",
    primaryProtein: "jackfruit",
    isClassic: false,
    instructions: [
      "Fry onion, garlic, ginger and curry spices until fragrant.",
      "Add tinned jackfruit and coconut milk, simmer 20 minutes, shredding the jackfruit as it softens.",
      "Serve with rice and coriander.",
    ],
    ingredients: [
      { name: "tinned jackfruit", quantity: "2 tins" },
      { name: "coconut milk", quantity: "400ml" },
      { name: "curry powder", quantity: "2 tbsp" },
      { name: "rice", quantity: "300g" },
      { name: "onion", quantity: "1" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "ginger", quantity: "20g" },
      { name: "fresh coriander", quantity: "1 handful" },
      { name: "vegetable oil", quantity: "1 tbsp" },
    ],
  },
  {
    name: "Falafel Bowl",
    description: "Crispy falafel with hummus, salad and warm flatbread.",
    primaryProtein: "chickpeas",
    isClassic: false,
    instructions: [
      "Blend chickpeas, herbs, garlic and spices, shape into falafel and fry until crisp.",
      "Assemble bowls with hummus, salad, pickles and falafel.",
      "Serve with warm flatbread and a drizzle of tahini.",
    ],
    ingredients: [
      { name: "chickpeas", quantity: "2 tins" },
      { name: "hummus", quantity: "200g" },
      { name: "flatbreads", quantity: "4" },
      { name: "tahini", quantity: "2 tbsp" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "flat leaf parsley", quantity: "1 handful" },
      { name: "ground cumin", quantity: "1 tsp" },
      { name: "mixed salad", quantity: "100g" },
      { name: "pickles", quantity: "50g" },
      { name: "vegetable oil", quantity: "500ml" },
    ],
  },
  {
    name: "Aubergine Parmigiana",
    description: "Layered fried aubergine, tomato sauce and melted cheese.",
    primaryProtein: "aubergine",
    isClassic: false,
    instructions: [
      "Fry sliced aubergine until golden.",
      "Layer with tomato sauce, mozzarella and parmesan in a dish.",
      "Bake at 190C for 25 minutes until bubbling and golden.",
    ],
    ingredients: [
      { name: "aubergines", quantity: "2" },
      { name: "tomato passata", quantity: "400ml" },
      { name: "mozzarella", quantity: "150g" },
      { name: "parmesan", quantity: "50g" },
      { name: "olive oil", quantity: "4 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
  },
  {
    name: "Sri Lankan Dhal",
    description: "Coconut red lentil dhal with warming curry spices.",
    primaryProtein: "lentils",
    isClassic: false,
    instructions: [
      "Fry onion, garlic, ginger, mustard seeds and curry leaves.",
      "Add red lentils, coconut milk and water, simmer 20 minutes until creamy.",
      "Season and serve with rice or flatbread.",
    ],
    ingredients: [
      { name: "red lentils", quantity: "250g" },
      { name: "coconut milk", quantity: "400ml" },
      { name: "curry leaves", quantity: "10" },
      { name: "mustard seeds", quantity: "1 tsp" },
      { name: "onion", quantity: "1" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "ginger", quantity: "20g" },
      { name: "vegetable oil", quantity: "1 tbsp" },
      { name: "rice", quantity: "250g" },
      { name: "salt", quantity: "to taste" },
    ],
  },
];

async function seed() {
  let insertedCount = 0;
  let updatedIngredientsCount = 0;
  let skippedPricedCount = 0;

  for (const m of DEMO_MEALS) {
    // Upsert by name — safe to re-run after editing DEMO_MEALS (e.g.
    // expanding ingredient lists) without disturbing a user's swipe
    // progress (approved_queue, meal_history, etc. are keyed by meal id,
    // which is preserved). Meals already priced via the real pricing
    // adapter (signalled by a priced ingredient row, not meals.tier —
    // seeded meals never get a placeholder tier, only real pricing sets
    // one) are left completely alone — never overwrite real SKU/price data.
    const existing = await db.query.meals.findFirst({ where: eq(meals.name, m.name) });

    if (existing) {
      const pricedIngredient = await db.query.mealIngredients.findFirst({
        where: and(eq(mealIngredients.mealId, existing.id), isNotNull(mealIngredients.skuPrice)),
      });
      if (pricedIngredient) {
        skippedPricedCount++;
        continue;
      }
      await db.delete(mealIngredients).where(eq(mealIngredients.mealId, existing.id));
      await db.insert(mealIngredients).values(
        m.ingredients.map((i) => ({
          mealId: existing.id,
          genericName: i.name,
          quantity: i.quantity,
        }))
      );
      updatedIngredientsCount++;
      continue;
    }

    // Deliberately no cost/tier here — meals start unpriced (NULL) and only
    // get a real cost/tier from priceApprovedMeals() (real pricing data).
    const [inserted] = await db
      .insert(meals)
      .values({
        name: m.name,
        description: m.description,
        instructions: m.instructions,
        primaryProtein: m.primaryProtein,
        isClassic: m.isClassic,
      })
      .returning({ id: meals.id });

    await db.insert(mealIngredients).values(
      m.ingredients.map((i) => ({
        mealId: inserted.id,
        genericName: i.name,
        quantity: i.quantity,
      }))
    );
    insertedCount++;
  }
  console.log(
    `Seeded ${insertedCount} new meals, refreshed ingredients on ${updatedIngredientsCount} existing meals, ` +
      `left ${skippedPricedCount} already-priced meals untouched.`
  );
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
